version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "thundra-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-86xal9kmqc48"
s3_prefix = "thundra-test"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

