AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Exploring Chaos Engineering

  AWS SAM project for exploring Latency Monkeys

Parameters:
  ThundraAWSAccountNo:
    Type: Number
    Default: 269863060030
  ThundraNodeLayerVersion:
    Type: Number
    Default: 24 # Or use any other version
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:    
    Runtime: provided
    Timeout: 5
    Environment:
      Variables:
          thundra_apiKey: API-KEY
    Layers:
      - !Sub arn:aws:lambda:${AWS::Region}:${ThundraAWSAccountNo}:layer:thundra-lambda-node-layer:${ThundraNodeLayerVersion}


Resources:
  ThundraTestFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: thundra-test/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        ThundraTest:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /thundra
            Method: get
  ChaoticThundraTestFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: thundra-test/
      Handler: app.chaoticLambdaHandler
      Runtime: nodejs12.x
      Events:
        ThundraTest:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /thundra-chaotic
            Method: get
  ThundraSpanListenerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: thundra-test/
      Handler: app.spanListenerLambdaHandler
      Runtime: nodejs12.x
      Events:
        ThundraTest:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /thundra-span
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ThundraTestApi:
    Description: "API Gateway endpoint URL for Prod stage for Thundra Test function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/thundra/"
  ThundraTestFunction:
    Description: "Thundra Test Lambda Function ARN"
    Value: !GetAtt ThundraTestFunction.Arn
  ThundraTestFunctionIamRole:
    Description: "Implicit IAM Role created for Thundra Test function"
    Value: !GetAtt ThundraTestFunctionRole.Arn
  ChaoticThundraTestFunction:
    Description: "Larry Presents the Thundra Test Lambda Function ARN"
    Value: !GetAtt ChaoticThundraTestFunction.Arn
  ChaoticThundraTestFunctionIamRole:
    Description: "Implicit IAM Role created for Larry's Thundra Test function"
    Value: !GetAtt ChaoticThundraTestFunctionRole.Arn
